# Generated by Django 5.2.5 on 2025-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
